### ISSUE TITLE
Please remove main activity

### ISSUE THREAD

**Issue by theScrabi** [tengusw/share_to_clipboard#11]
Hello. Your app is usefull. Although i'd like it without a launcher icon, since you barely use it.

**Comment by KashifAnwaar** [comment]
No, don't remove anyone, i am about to contribute features and settings which are accessed in main activity.

**Comment by tasn** [comment]
@theScrabi, you are not the first one to ask for that. I think we will have an option from the settings page to hide it permanently. with that being said, you'll be missing @KashifAnwaar's features. :P 

@KashifAnwaar, cool! Looking forward to reviewing the patches.

**Comment by tasn** [comment]
@theScrabi, btw, just to provide more info, the reason why we added it is that users kept on calling this app a virus on Google Play because they couldn't find the launcher, or because they couldn't understand how to use it. We thus decided to add a launcher with instructions.

**Comment by theScrabi** [comment]
ok i see.

**Comment by tasn** [comment]
Fixed in ff2713e237d0db6d840fc0067d47da48ffbcb233, and released in v1.5.0.
