### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 1.4.0.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [tengusw/share_to_clipboard#12]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 1.4.0.

**Comment by tasn** [comment]
Fair point, thanks!

Looking at https://github.com/tengusw/share_to_clipboard/releases, it doesn't seem like tag content is available unless you expand (by clicking on the ellipsis button). Do you know if there's a way for GitHub to expand it by default? We can start adding change log information in tags, I'm happy with that, but I don't want to use the github interface.

**Comment by locutis-of-borg-1999** [comment]
Some just point to their "releases" page, others, to a simple text file.  
  
https://f-droid.org/manual/html_node/Changelog.html#Changelog

**Comment by tasn** [comment]
That's not what I was asking. I was trying to see if I could use GitHub's support for showing tag messages in the UI without using the GitHub UI. Doesn't seem to be the case, so I'll have to manage a ChangeLog file manually.

**Comment by tasn** [comment]
Added a changelog file: https://github.com/tengusw/share_to_clipboard/blob/master/ChangeLog.md
I asked @talhacohen to update the link on fdroid, so will be done soon.
