### ISSUE TITLE
FastHub Gists support 

### ISSUE THREAD

**Issue by Tajnymag** [tengusw/share_to_clipboard#14]
I've just tried to share a gist from FastHub app and got an error saying that Share to Clipboard doesn't support such format. 

Could you look into it, please? 

I'm running Lineageos 14.1 (Android 7.1)

**Comment by talhacohen** [comment]
Thank you very much for your feedback.
FastHub are using the generic MIME type text/* which is not supported in the app currently. 
We will support it in the next version, In addition, I opened an [issue](https://github.com/k0shk0sh/FastHub/issues/705) in FastHub to fix it.

**Comment by talhacohen** [comment]
Fixed in [commit 1acba282b2d9e952af9517440e8f87894dff742b](https://github.com/tengusw/share_to_clipboard/commit/1acba282b2d9e952af9517440e8f87894dff742b)

**Comment by Tajnymag** [comment]
@talhacohen Thank you :)
