### ISSUE TITLE
Share To Clipboard doesn't pop up when I click share.

### ISSUE THREAD

**Issue by ReportingRaccoon** [tengusw/share_to_clipboard#17]
Hello,
Share To Clipboard is not showing itself for me. I am clicking share, there are other apps but no "Clipboard" is available. Tried to run it before sharing, reinstalling - but it just not seem to work.

Im using latest version, EMUI 5.0 Nougat

**Comment by talhacohen** [comment]
Hey, 
What did you try to share? from what app? 
I'll take a look at it.
Thanks for reporting

**Comment by ReportingRaccoon** [comment]
Insight Timer, I wanted to copy the e-mail adress in help section. I think it's caused by Share To Clipboard is not triggered as an e-mail app, so we can't copy emails

**Comment by talhacohen** [comment]
Thanks.
They used mime type RFC822 which we didn't support.
We will release a new version in the coming days that solves this issue.

Thanks you very much for reporting the issue and we hope that you will
enjoy the app,
Tal

**Comment by talhacohen** [comment]
For example, for insight timer you will get:

> help@insight.co
> Insight Timer Support (Android) - Android: 8.0.0
> Device model: OnePlus ONEPLUS A3003
> App version: 12.4.12.252
> 
>
