### ISSUE TITLE
Increase priority in share menu

### ISSUE THREAD

**Issue by smichel17** [tengusw/share_to_clipboard#18]
This app is great and I use it quite frequently. Therefore, I would prefer if it always appeared on the first page (top 8 apps) in the share menu, so I can access it faster (although I don't want to make it the default because I don't always use it).

I'm not sure how Android decides what order to show items in / whether it's  possible to change that. If not, an alternative would be to show a "toast with action"\* (like Firefox opening tabs in the background), where the action re-shares the content to a different app (and then I'd set this as the default).

\*I haven't looked at the code but I think it's not actually a toast, just a view shown via overlay

**Comment by tasn** [comment]
I'm also maddened by the seemingly arbitrary order in the share menu. I'm using LineageOS and it definitely doesn't work as I would expect (frequency of use). I don't think this can be controlled by the apps themselves, but maybe @talhacohen knows otherwise.

The Firefox idea is an interesting one, though I think it'll require the "draw over other apps" permission, which would make it a bit annoying and scarier for new users, so I'm a bit reluctant. Maybe we can emulate that with a transparent activity, a trick I think we already utilise.

@talhacohen, what are your thoughts? What's possible to achieve?

**Comment by smichel17** [comment]
> seemingly arbitrary order in the share menu.

On my Galaxy S6, Android 7.0.1, it seems like frequent usage does promote items, but only temporarily.

> I don't think this can be controlled by the apps themselves

IIRC, **intents,** are ordered at least in part by the specificity of events you register to recieve. Ex: when you open a github link, github apps will appear before browsers because they only recieve that domain.  I'm not sure if that also holds for sharing.

> "draw over other apps" permission [...] transparent activity

I think an activity would have to intercept taps on the whole screen, though, right? A nice thing about the Firefox behavior is that you can still keep using whatever app you're currently in.

If I were to implement the firefox-like behavior, I would make it a setting in the app. Then...
Easy way: When the setting is enabled,  if the permission is not granted, show a dialog explaining why we are requesting it.
Harder way: When the setting is on but the permission is not granted, fall back to a transparent activity and provide a prompt (eg, snackbar at the bottom of the app, "Feature would work better with permissions", with an action to request them).

Another alternative: when something is copied to the clipboard, show a notification until it is pasted for the first time, that includes an action to share to a different app.

**Comment by talhacohen** [comment]
I don't thing it's possible to change the order of the apps in the share menu, I will take a look on it.

The firefox sounds interesting. I agree with @tasn that adding that permission is not a good idea, as the average user will not use that and I think it will be scary for new users. 

Adding notification is possible, and will not require any other permission which is good. @tasn what do you think? 

Anyway, I will search for more alternatives

**Comment by tasn** [comment]
> On my Galaxy S6, Android 7.0.1, it seems like frequent usage does promote items, but only temporarily.

Same here.

> IIRC, intents, are ordered at least in part by the specificity of events you register to recieve. Ex: when you open a github link, github apps will appear before browsers because they only recieve that domain. I'm not sure if that also holds for sharing.

Makes sense, but unfortunately we can't be more specific.

> I think an activity would have to intercept taps on the whole screen, though, right? A nice thing about the Firefox behavior is that you can still keep using whatever app you're currently in.

In firefox it happens within firefox itself if memory serves, so they can do that. I don't remember this, nor do I think it's such an important feature to maintain. If you are sharing, just share.

> 
> If I were to implement the firefox-like behavior, I would make it a setting in the app. Then...
> Easy way: When the setting is enabled, if the permission is not granted, show a dialog explaining why we are requesting it.
> Harder way: When the setting is on but the permission is not granted, fall back to a transparent activity and provide a prompt (eg, snackbar at the bottom of the app, "Feature would work better with permissions", with an action to request them).

You see the amount of complication we are adding? This alone is more costly than the occasional scroll for some of the users. The hopeful, never gonna happen, solution would be to have it fixed in Android. However the workaround as described above is a bit too much.

> 
> Another alternative: when something is copied to the clipboard, show a notification until it is pasted for the first time, that includes an action to share to a different app.

@talhacohen, are we able to see when a paste has occurred? I think not.

One solution would be to open an activity and let you choose if copy or propagate, but I don't like this one, as it works around the normal sharing mechanism of android.
The other, and what I think is the best solution would be a timed notification, that is a notification that disappears after X seconds, that does what you described.
Either solution would be hidden behind a setting.

@smichel17 what do you think?

I can unfortunately feel your pain, as I suffer from the same annoying ordering issue, though to be honest, I suffer with it also with an array of other apps, and not just share to clipboard.

**Comment by talhacohen** [comment]
I don't think its possible to detect a paste event without having any view, couldn't find any solution for that.

**Comment by smichel17** [comment]
How's this: when someone shares to clipboard, instead of displaying a "Copied to clipboard" *toast*, display a "Copied to clipboard" *heads-up notification.* Tapping the notification re-shares the thing, so you could open it with a different app even if this app is the default. After 2 (?) seconds or when it is swiped away, we dismiss the notification.

In essence, we're doing the firefox thing using the notification system instead of an overlay.

**Comment by tasn** [comment]
What do you mean by heads-up notification? Do you mean popup? Do those still exist?

Yes, I think a timing out notification (probably longer than 2 seconds) would be a good solution, and just to clarify, with a configuration option to disable (maybe just a configuration to set the time out of preset values, one of which means off?). Default should probably be off.

I think I'm happy with this solution, @talhacohen?

**Comment by talhacohen** [comment]
Sounds good. I'll add that option to next release.

Just to summarize, when copying using the app, if configured in the
settings, a notification with share to other apps will appear to X
sec(according to configuration)

**Comment by tasn** [comment]
Correct.

**Comment by smichel17** [comment]
> What do you mean by heads-up notification? Do you mean popup?

Yes, where it's visible at the top of the screen (as opposed to only visible from the notification shade).

> probably longer than 2 seconds

The idea behind two seconds was: if I actually want to share to a different app, not clipboard, I'm going to do so immediately, by tapping the notification while it is visible at the top of the screen, not by opening the shade 10s later. At the same time, just because I shared something to the clipboard, doesn't mean I want a notification sitting at the top of the screen for a long time.

So, the idea was basically, show the notification for the same amount of time that we currently show the toast for (maybe that's longer than 2s), then dismiss it.

Maybe we could leave it around for a while the first time, or until the user taps it for the first time, or something like that, but I honestly don't think it would be that useful.  Instead of making it configurable from the start,  why don't we try setting it to something short at first and see if anyone asks it to be lengthened?

**Comment by tasn** [comment]
I thought heads-up notifications were just automatic, but apparently there's a way to influence them so they happen more reliably:

https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Heads-up

Though it seems that there's a way to make it work reliably:

https://stackoverflow.com/questions/26451893/heads-up-notification-android-lollipop

I'd say: @talhacohen , see if you can make the heads-up work reliably. If you can, great, let's just do that with 3s or so (I think reading what it is will take longer than 2 secs for some non natives), if you can't we'll have to do the time configurable notification version as suggested above.

@smichel17, thanks for all the great ideas!

**Comment by smichel17** [comment]
This (unmaintained afaict) project can make heads up notifications as far back as api 16, although I think it might use permissions we want to avoid: https://github.com/AChep/HeadsUp

**Comment by talhacohen** [comment]
Thanks all, I'll work on it in a week or two

**Comment by smichel17** [comment]
> I think reading what it is will take longer than 2 secs for some non natives

I'm imagining something like:

Primary text: "Copied to clipboard"
Secondary text: "Tap here to share to a different app instead."

The first time, we can leave the notification pinned to the top indefinitely (or, as long as possible), until it is tapped or manually dismissed. This gives people as much time as they want/need to read it, and lets us assume that they have done so. After that point, it's safe to dismiss it after 2-3 seconds.

**Comment by talhacohen** [comment]
> edit: that is, I know it uses permissions we don't want (accessibility service, iirc), so it can heads-up-ify the notifications of other apps; I'm not sure whether those are needed to create the heads up notification or not.
I'll take a look on that, in case it will not require additional permission I'll use that, otherwise, I'll do the headsup only for Android 21+ and will do normal notifications for older devices with settings.

**Comment by talhacohen** [comment]
We added the feature into the next version.

Would you mind if we mention you in the README file as a contributor? 
Thanks!

**Comment by smichel17** [comment]
I don't mind :)
