### ISSUE TITLE
Update ez-vcard dependency

### ISSUE THREAD

**Issue by hugomg** [tengusw/share_to_clipboard#27]
The latest version of [ez-vcard](https://github.com/mangstadt/ez-vcard) is 0.10.6. We should also check if some of the latest updates would let us improve our code a little bit.

**Comment by tasn** [comment]
I'd be happy to accept a PR to update the version if there aren't any code improvements, but what kind of code improvements are you expecting?

**Comment by hugomg** [comment]
The [changelog](https://github.com/mangstadt/ez-vcard/wiki/Changelog) mentioned a new toString method added in version 0.9.9 and I wondered if that would allow us to simplify the arrayToString code. After looking into it I don't think that is actually the case because the new toString outputs a programmer-friendly string instead of an user-friendly one. That said, I did find it very useful for debugging with Log.d.

The only code improvement I still want to add is a small change to the vCard parsing code to use the [VCardReader class](https://github.com/mangstadt/ez-vcard/wiki/Plain-text#12-example) mentioned in the docs.

There are also two things that I didn't understand about the current code, that I am asking about in #29. We may want to address those as well.

**Comment by tasn** [comment]
I'm fine with the update and your suggestions.
As for #29, I asked @talhacohen to comment about it, as he wrote the code, and hopefully he'll be able to do it today.
