### ISSUE TITLE
Weird code in handleRfc822Message

### ISSUE THREAD

**Issue by hugomg** [tengusw/share_to_clipboard#29]
[This code](https://github.com/tengusw/share_to_clipboard/blob/700e13250cf0b146c4b8924da1f75aedded73992/app/src/main/java/com/tengu/sharetoclipboard/ShareToClipboardActivity.java#L139) looks like it should have been doing `email +=` instead of `email =`. 

```
String email = emails[0];
for (int i = 1; i < emails.length; i++) {
    email = ", " + emails[i];
}
```

Would you be able to help me understand when handleRfc822Message is normally called?

**Comment by hugomg** [comment]
A also have a question about the [arrayToString](https://github.com/hugomg/share_to_clipboard/blob/ba15ad74db4fc0ce8336b8e790681dede2af75e6/app/src/main/java/com/tengu/sharetoclipboard/ShareToClipboardActivity.java#L125) function. It doesn't add any separators between the items. I would have expected it to add a apace or comma between them.

        StringBuilder result = new StringBuilder();
        for (Object value : objectArray) {
            String s = value.toString();
            if (!s.equals("pref")) {
                result.append(capitalize(s));
            }
        }

However, I also couldn't manage to produce a test case where a contact has a phone number with more than two types. Do you know how I could do that?

I tried using android contacts app and adding the same phone number twice but with different types. But when I did that the vCard produced by the contacts app would appear to only return the first type. For example, if I added the same phone number as "Preferential" and as "Work" the contacts app would only return the "Preferential" type and arrayToString would render it as "Other".

**Comment by talhacohen** [comment]
I don't remember when handleRfc822Message is called or why it was added. We can create a new intent using the rfc822 type to test that flow, though I don't remember a real usage for it. 

Re arrayToString: it indeed looks like a bug. I'm not sure if it's possible to add more than 1 type for a contact. We should probably either always take the first, or add a Comma separator

**Comment by tasn** [comment]
Just to add in case you haven't tried: `git blame` is a very valuable tool for figuring out what commit introduced a line of code, and maybe from the commit message, you can figure out why it was added in the first place.

**Comment by hugomg** [comment]
> Re arrayToString: it indeed looks like a bug. I'm not sure if it's possible to add more than 1 type for a contact. We should probably either always take the first, or add a Comma separator

Without knowing things for sure I think it would be better to show everything separated by comas, to avoid throiwing away data if it is there.

I got rid of the special logic about the "Pref" type because I think it only made sense if there were multiple types. Now if something is marked as Preferential it will not show up as "Other".

> I don't remember when handleRfc822Message is called or why it was added.

Thanks for the git blame suggestion. Why didn't I think of that before?

Aparently, this email handling feature this was added in response to #17. My question now is if we really need to have this feature. I think it is a bit confusing that Share to Clipboard advertises itself as an email app and appears as an option when we try to send an email to someone. My expectation was that Share to Clipboard would only show up when pressing a "Share" button, which is not what is happening when we click a "mailto:" link.

**Comment by tasn** [comment]
That's a fair point about `mailto:` not being "share". Though I don't necessarily think we should limit the app's functionality just because the app's name if the functionality makes sense and is in scope.
Especially since, in many apps, sharing means sending an email, like what #17 was referring to.

If users don't like it, they can just choose a different mail client, Android was designed with this in mind. So I don't think it's a problem.

**Comment by hugomg** [comment]
The default behavior that happens after clicking on a mailto link is to open an e-mail client such as GMail or K9-Mail, which brings up an activity for writing an email to the specified address. In that activity the email address and the message body appear in an editable text field and can be copied to the clipboard without Share to Clipboard's help.

I wonder if what might have confused OP in issue #17 is that clicking a "mailto" link brings up a "choose an app" menu which is superficially similar to a share-with menu. However, I am not sure it is in scope for Share to Clipboard to insert itself in every "open with" menu out there, just in case the user might want to copy something.

One of the downsides of pretending to be able to open things that you can't actually open is that the system may offer to set Share to Clipboard as the default app for that file type. If we choose to "always" open maito links with Share to Clipboard instead of "just once" then Share to Clipboard will hijack every attempt to send an email and the only way to undo that is hidden deep inside the system settings.

**Comment by tasn** [comment]
I agree with your line of thinking, and I guess we can remove this behaviour. I don't think anyone will complain about this being gone, so please go ahead and open a PR.
