### ISSUE TITLE
Should we stop handling VIEW and DIAL intents for email and phone numbers?

### ISSUE THREAD

**Issue by hugomg** [tengusw/share_to_clipboard#31]
As discussed in #29, there are some issues with handling VIEW and DIAL intents for email and phone numbers:

* VIEW and DIAL intents are not the result of the user pressing a "Share" button. Typical sharing intents use the SEND intents.
* When the users chooses what app to use to open a VIEW or DIAL intent, Android asks if the app should be used "Just once" or "Always". If the user accidentally sets Share to Clipboard as the default handler for that task then it will hijack future attempts to send emails or call phone numbers.
  * The only way to undo this is to go to system settings, under Apps and Notifications.
  * If notifications are disabled then there is no visual or audible feedback to show that Share to Clipboard is hijacking the VIEW or DIAL intent.
* Share to Clipboard's functionality is not strictly necessary for these intents because email clients and phone dialers already put the relevant data in an editable textbox. The user can use regular copy/paste to copy the email address or the phone number.

I propose that we trim down the list of intents that Share to Clipboard handles. I think we should get rid of VIEW and DIAL intent filters for phone numbers and email and keep the SHARE intent filter for text and v-cards.

**Comment by tasn** [comment]
I can't remember what the reasoning was, but I think it must have been that not all mail clients let you easily copy the recipients or something of this sort. Anyhow, I'm fine with this suggestion.

**Comment by tasn** [comment]
I'm closing this, let's discuss it at #31, no point in having the discussion split.
