### ISSUE TITLE
Should we give some visual feedback if notifications are disabled?

### ISSUE THREAD

**Issue by hugomg** [tengusw/share_to_clipboard#33]
It would be nice if we always gave some visual feedback after copying something, even if notifications are disabled.

In versions of AOSP that come with a built-in "share to clipboard" feature, there is a toast to provide that visual feedback. This is also what this app used to do before commit [bac353b6](https://github.com/tengusw/share_to_clipboard/commit/bac353b66f052105a2a1e4e156b8cc84c3715c31), which introduced the re-sharing notification.

**Comment by tasn** [comment]
As mentioned in https://github.com/tengusw/share_to_clipboard/pull/32#issuecomment-629084377, I think having a toast when the notification is disabled makes sense.
