### ISSUE TITLE
vcard parsing use-case disadvantage

### ISSUE THREAD

**Issue by tcecyk** [tengusw/share_to_clipboard#50]
I looked for a way to share plain vcard text to binaryeye - a qrcode generator - to share as vcard qrcode.

With vcard parsing, this route is barred.

Would you consider putting the vcard parsing behind a option switch?

**Comment by tasn** [comment]
Why is it barred? On Android you can choose which apps to open what with. Just don't have share-to-clipboard selected for vcards. Have the other app instead.

**Comment by tcecyk** [comment]
it's really a shortcoming of the preferred qrcode reader to not show up in the share menu for vcf files from the AOSP contacts app -> will very likely get integrated at some point in time.

I looked for a general-purpose clipboard tool to use as intermediary.

As the vcard is parsed, it looses this markup that I'd like to rely on. For others, the majority, this is a desireable feature to get rid of the markup for pasting.

I'm sorry to have raised this, you can close this, I will put myself behind a PR for the qrcode app.
